# Nome do meu programa
NAME := push_swap

# Aqui eu pego as bibliotecas 
LIBFT_DIR := libft
PRINT_F_DIR := printf
# Diretório atual onde está push_swap.h
INCLUDE_DIR := .

# Compilar com as flags da 42
CC := cc
CFLAGS := -Wall -Werror -Wextra